# Generated by Django 2.2.7 on 2019-12-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191223_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-reg_date'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'Users Profiles'},
        ),
    ]
