# Generated by Django 2.2.7 on 2019-12-23 14:07

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191223_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text="<b style='color:red'>Do Not Edit</b>", unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='value',
            field=models.CharField(default=core.helpers.getUniqueId, max_length=50),
        ),
    ]
