# Generated by Django 2.2.7 on 2019-12-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191223_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='value',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='tags',
            name='color',
            field=models.CharField(choices=[('purple', 'purple'), ('secondary', 'secondary'), ('danger', 'danger')], default='purple', max_length=50),
        ),
    ]
