# Generated by Django 2.2.7 on 2019-12-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191223_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-start_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='item',
            name='label_type',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1, verbose_name='Product Label Type'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(choices=[('purple', 'purple'), ('secondary', 'secondary'), ('danger', 'danger'), ('blue-text', 'blue-text'), ('cyan', 'cyan'), ('light-blue', 'light-blue'), ('yellow', 'yellow'), ('amber', 'amber'), ('light-green', 'light-green'), ('indigo', 'indigo'), ('lime', 'lime'), ('brown', 'brown'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('deep-purple', 'deep-purple'), ('deep-purple', 'deep-purple')], default='purple', max_length=50),
        ),
    ]
