# Generated by Django 2.2.7 on 2019-12-25 15:37

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191224_2048'),
        ('shop', '0008_auto_20191224_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='message',
            field=models.CharField(blank=True, help_text='Message from Paystack', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Reference from Paystack', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, help_text='Status string from Paystack', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='trans',
            field=models.CharField(blank=True, help_text='trans from Paystack', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction from Paystack', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='trxref',
            field=models.CharField(blank=True, help_text='Trxref from Paystack', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='uid',
            field=models.CharField(default=core.helpers.getUniqueId, editable=False, help_text='Internal reference ID', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount Paid in Naira (₦)', max_digits=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.UserProfile'),
        ),
        migrations.CreateModel(
            name='Fashioninsta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, default=core.helpers.getUniqueId, editable=False, help_text="<b style='color:red'>Do Not Edit</b>", max_length=20, null=True, unique=True)),
                ('neck', models.IntegerField(blank=True, null=True, verbose_name='Neck')),
                ('shoulder', models.IntegerField(blank=True, null=True, verbose_name='Shoulder')),
                ('chest', models.IntegerField(blank=True, null=True, verbose_name='Chest')),
                ('tommy', models.IntegerField(blank=True, null=True, verbose_name='Tommy')),
                ('sleeve', models.IntegerField(blank=True, null=True, verbose_name='Sleeve Length')),
                ('biceps', models.IntegerField(blank=True, null=True, verbose_name='Biceps')),
                ('round_sleeve', models.IntegerField(blank=True, null=True, verbose_name='Round Sleeve')),
                ('wrist', models.IntegerField(blank=True, null=True, verbose_name='Cuff/Wrist')),
                ('shirt', models.IntegerField(blank=True, null=True, verbose_name='Shirt Length')),
                ('trouser_waist', models.IntegerField(blank=True, null=True, verbose_name='Trouser Waist')),
                ('trouser_lenght', models.IntegerField(blank=True, null=True, verbose_name='Trouser Lenght')),
                ('hip', models.IntegerField(blank=True, null=True, verbose_name='Sit/Hip')),
                ('laps', models.IntegerField(blank=True, null=True, verbose_name='Laps')),
                ('knee', models.IntegerField(blank=True, null=True, verbose_name='Knee')),
                ('calf', models.IntegerField(blank=True, null=True, verbose_name='Calf')),
                ('ankle', models.IntegerField(blank=True, null=True, verbose_name='Base/Ankle')),
                ('description', models.TextField(blank=True, max_length=350, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('done', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='shop.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_requests', to='core.UserProfile')),
            ],
            options={
                'verbose_name': 'Fashion Request',
                'verbose_name_plural': 'Fashion Requests',
                'ordering': ['-timestamp'],
            },
        ),
    ]
