# Generated by Django 2.2.7 on 2019-12-26 16:38

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20191226_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashioninsta',
            name='slug',
            field=models.CharField(blank=True, default=core.helpers.getUniqueId, editable=False, help_text="<b style='color:red'>Do Not Edit</b>", max_length=50, null=True, unique=True),
        ),
    ]
