# Generated by Django 2.2.7 on 2019-12-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20191226_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='complete',
        ),
    ]
